runtime: python312

env_variables:
  API_KEY: "bd5e378503939ddaee76f12ad7a97608"  

handlers:
  - url: /
    script: auto

health_check:
  enable_health_check: True

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
