runtime: python39

env_variables:
  API_KEY: "bd5e378503939ddaee76f12ad7a97608"  # Ensure you replace this with your valid API key or use Secret Manager for sensitive data

handlers:
  - url: /
    script: auto

# Optionally, include health checks
health_check:
  enable_health_check: True

# Additional settings for scaling
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
